CREATE TABLE IF NOT EXISTS world_details (
  id SERIAL PRIMARY KEY,
  foundation_id INTEGER NOT NULL REFERENCES foundations(id),
  world_name TEXT NOT NULL,
  narrative_context TEXT,
  global_geography_topography TEXT,
  regions_territories TEXT,
  boundaries_borders TEXT,
  climate_environmental_zones TEXT,
  environment_placements_distances TEXT,
  resources_economic_geography TEXT,
  historical_cultural_geography TEXT,
  speculative_supernatural_geography TEXT,
  map_generation_details TEXT,
  inspirations_references TEXT,
  era TEXT,
  description TEXT,
  geography TEXT[],
  locations TEXT[],
  culture JSONB,
  politics JSONB,
  economy JSONB,
  technology JSONB,
  conflicts TEXT[],
  history JSONB,
  magic_system JSONB,
  thread_id TEXT,
  embedding_json JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);